// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {disk} from '../models';
import {main} from '../models';

export function ElevatePrivileges(arg1:string):Promise<boolean>;

export function GetDisks():Promise<Array<disk.Info>>;

export function GetSnapStatus():Promise<main.SnapStatus>;

export function IsRoot():Promise<boolean>;

export function RecoverFiles(arg1:string,arg2:string):Promise<string>;

export function RepairFS(arg1:string):Promise<string>;

export function ScanPartitions(arg1:string):Promise<string>;

export function StartClone(arg1:disk.CloneOptions,arg2:string):Promise<string>;
