// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ElevatePrivileges(arg1) {
  return window['go']['main']['App']['ElevatePrivileges'](arg1);
}

export function GetDisks() {
  return window['go']['main']['App']['GetDisks']();
}

export function IsRoot() {
  return window['go']['main']['App']['IsRoot']();
}

export function RecoverFiles(arg1, arg2) {
  return window['go']['main']['App']['RecoverFiles'](arg1, arg2);
}

export function RepairFS(arg1) {
  return window['go']['main']['App']['RepairFS'](arg1);
}

export function ScanPartitions(arg1) {
  return window['go']['main']['App']['ScanPartitions'](arg1);
}

export function StartClone(arg1, arg2) {
  return window['go']['main']['App']['StartClone'](arg1, arg2);
}
