name: Snapcraft Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wails Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev npm
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build Snap
        run: |
          sudo snap install snapcraft --classic
          # O sudo -E preserva o PATH configurado para que o comando wails seja encontrado
          sudo -E snapcraft pack --destructive-mode
          echo "snap=$(ls *.snap | head -n 1)" >> $GITHUB_OUTPUT
        id: build

      - name: Fix snapcraft log permissions
        run: sudo chown -R runner:runner /home/runner/.local/state/snapcraft || true

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clonarmidia-snap
          path: ${{ steps.build.outputs.snap }}

      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
